apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: sb-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: sbali21/sb-todo-app
        name: worker
        ports:
        - containerPort: 8501
