apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  type: NodePort
  ports:
  - name: "todo-app-service"
    port: 8501
    targetPort: 8501
    nodePort: 31002
  selector:
    app: todo-app